# Enable all rules to see what we're actually not complying with
opt_in_rules:
  - all

# Disable overly strict or problematic rules (matching UIComponents)
disabled_rules:
  # We should keep
  - contrasted_opening_brace
  - explicit_acl
  - file_types_order
  - one_declaration_per_file
  - type_contents_order
  - redundant_type_annotation
  - extension_access_modifier
  - redundant_string_enum_value

  # Major refactoring required (hundreds/thousands of violations)
  - no_magic_numbers # 462 violations - Hard-coded numeric values
  - indentation_width # 188 violations - Indentation consistency
  - force_unwrapping # 132 violations - Force unwrapping should be avoided
  - explicit_top_level_acl # 116 violations - Top-level declarations need access control

  # Medium effort to fix (50-100 violations)
  - no_empty_block # 106 violations - Empty code blocks
  - sorted_enum_cases # 100 violations - Enum case ordering
  - conditional_returns_on_newline # 62 violations - Return placement
  - file_name # 52 violations - File naming

  # Low effort to fix (under 50 violations)
  - discouraged_optional_collection # 46 violations - Prefer empty over optional
  - function_body_length # 10 violations - Function length limits (would break tests if refactored)
  - cyclomatic_complexity # 8 violations - Function complexity
  - type_body_length # 10 violations - Type length limits (requires splitting types)
  - file_length # 19 violations - File length limits (requires splitting files)
  - closure_body_length # 9 violations - Closure length (complex refactoring needed)

# Make rules strict
strict: true

# Directories to include/exclude during linting
included:
  - Sources
  - Tests
excluded:
  - .build

# Customize rule parameters
line_length:
  warning: 120 # 810 violations - Lines over 100 characters
  error: 120


custom_rules:
  no_direct_color_literals:
    name: "No direct Color literals"
    regex: '(^|[^A-Za-z0-9_])Color[.](red|green|blue|orange|yellow|pink|purple|gray|black|white|clear|primary|secondary)'
    message: "Use UIComponents Color tokens (UIComponents/Sources/UIComponents/Color.swift) instead of Color.red/Color.gray/etc."
    severity: error
  no_color_primary_secondary_shorthand:
    name: "No .primary/.secondary shorthand"
    regex: '[.](foregroundColor|foregroundStyle)[(][ ]*[.](primary|secondary)[ ]*[)]'
    message: "Use Color.textPrimary/Color.textSecondary (tokens) instead of .primary/.secondary."
    severity: error
  no_system_color_constructors:
    name: "No UIColor/NSColor construction"
    regex: '(^|[^A-Za-z0-9_])Color[(][ ]*(UIColor|NSColor)[.]'
    message: "Use UIComponents Color tokens backed by Assets.xcassets."
    severity: error
  no_rgb_color_construction:
    name: "No RGB Color construction"
    regex: '(^|[^A-Za-z0-9_])Color[(][ ]*(red[ ]*:|[.]sRGB)'
    message: "Define colors in UIComponents Assets.xcassets and expose via Color.swift."
    severity: error
  no_color_hex_initializer:
    name: "No Color(hex:) construction"
    regex: '(^|[^A-Za-z0-9_])(Color[(][ ]*hex[ ]*:|[.]init[(][ ]*hex[ ]*:)'
    message: "Use Color.userProvided(hex:) for user colors; otherwise define colors in Assets.xcassets."
    severity: error
