# Enable all rules to see what we're actually not complying with
opt_in_rules:
  - all

# Disable overly strict or problematic rules (matching UIComponents)
disabled_rules:
  # Same as UIComponents
  - contrasted_opening_brace
  - explicit_acl
  - file_types_order
  - one_declaration_per_file
  - type_contents_order
  - redundant_type_annotation
  - extension_access_modifier

  # AudioGenerator-specific exceptions
  - identifier_name # Domain-specific names like F0, i, x are meaningful in audio/ML context
  - vertical_parameter_alignment_on_call # Interferes with indentation fixes
  - type_body_length # KokoroTTS is complex ML implementation requiring longer class

  # Major refactoring required (hundreds/thousands of violations)
  - no_magic_numbers # 406 violations - Hard-coded numeric values (common in audio processing)

  # Medium effort to fix (50-100 violations)
  - indentation_width # 52 violations - Indentation consistency

  # Current batch: Too many violations to fix manually in one go
  - lower_acl_than_parent # Need to fix access control
  - number_separator # Need to add underscores to numbers
  - multiline_arguments_brackets # Need to fix bracket placement
  - missing_docs # Need to add documentation
  - conditional_returns_on_newline # Need to fix return formatting
  - superfluous_else # Need to remove unnecessary else
  - implicitly_unwrapped_optional # Need to replace ! with proper optionals
  - prefer_self_in_static_references # Need to add self.
  - no_empty_block # Need to add comments to empty blocks
  - attributes # Need to fix attribute placement

  # Complex violations requiring significant refactoring
  - discouraged_optional_collection # Complex API parameter changes needed
  - function_default_parameter_at_end # Complex parameter reordering needed
  - redundant_string_enum_value # Conflicts with explicit_enum_raw_value

  # Low effort to fix (under 50 violations)
  - unavailable_function # 4 violations - Abstract methods need different approach

# Make rules strict
strict: true

# Directories to include/exclude during linting
included:
  - Sources
  - Tests
excluded:
  - .build

# Customize rule parameters
line_length:
  warning: 150
  error: 200
  ignores_function_declarations: true
  ignores_comments: true
  ignores_urls: true

# Allow more parameters for complex initializers and functions
function_parameter_count:
  warning: 7
  error: 10

# Large tuples are sometimes needed in tests
large_tuple:
  warning: 4
  error: 5


custom_rules:
  no_direct_color_literals:
    name: "No direct Color literals"
    regex: '(^|[^A-Za-z0-9_])Color[.](red|green|blue|orange|yellow|pink|purple|gray|black|white|clear|primary|secondary)'
    message: "Use UIComponents Color tokens (UIComponents/Sources/UIComponents/Color.swift) instead of Color.red/Color.gray/etc."
    severity: error
  no_color_primary_secondary_shorthand:
    name: "No .primary/.secondary shorthand"
    regex: '[.](foregroundColor|foregroundStyle)[(][ ]*[.](primary|secondary)[ ]*[)]'
    message: "Use Color.textPrimary/Color.textSecondary (tokens) instead of .primary/.secondary."
    severity: error
  no_system_color_constructors:
    name: "No UIColor/NSColor construction"
    regex: '(^|[^A-Za-z0-9_])Color[(][ ]*(UIColor|NSColor)[.]'
    message: "Use UIComponents Color tokens backed by Assets.xcassets."
    severity: error
  no_rgb_color_construction:
    name: "No RGB Color construction"
    regex: '(^|[^A-Za-z0-9_])Color[(][ ]*(red[ ]*:|[.]sRGB)'
    message: "Define colors in UIComponents Assets.xcassets and expose via Color.swift."
    severity: error
  no_color_hex_initializer:
    name: "No Color(hex:) construction"
    regex: '(^|[^A-Za-z0-9_])(Color[(][ ]*hex[ ]*:|[.]init[(][ ]*hex[ ]*:)'
    message: "Use Color.userProvided(hex:) for user colors; otherwise define colors in Assets.xcassets."
    severity: error
