# Enable all rules to see what we're actually not complying with
opt_in_rules:
  - all

# Disable overly strict or problematic rules (matching UIComponents)
disabled_rules:
  # Same as UIComponents
  - contrasted_opening_brace
  - explicit_acl
  - file_types_order
  - one_declaration_per_file
  - type_contents_order
  - redundant_type_annotation
  - extension_access_modifier

  # Database-specific exceptions
  - blanket_disable_command # Sometimes needed for edge cases
  - superfluous_disable_command # Sometimes needed for edge cases
  - nesting # Allow nested types for command pattern
  - convenience_type # 32 violations - Test structs and command pattern structs
  - required_deinit # 38 violations - Not needed for SwiftData models

  # Major refactoring required (thousands of violations)
  - explicit_type_interface # 3050 violations - Would require adding type annotations everywhere
  - explicit_top_level_acl # 138 violations - Top-level access control
  - no_magic_numbers # 672 violations - Hard-coded numeric values
  - number_separator # 300 violations - Underscores in large numbers

  # Medium effort to fix (100-200 violations)
  - missing_docs # 166 violations - Public declarations need documentation
  - unused_closure_parameter # 202 violations - Unused parameters (rag, userId, context)
  - indentation_width # 108 violations - Indentation consistency
  - vertical_whitespace_between_cases # 100 violations - Empty lines between switch cases
  - force_unwrapping # 110 violations - Force unwrapping should be avoided

  # Very low effort to fix (fewer than 20 violations)
  - no_extension_access_modifier # 12 violations - Extension access modifiers
  - closure_body_length # 12 violations - Long closure bodies
  - function_body_length # 2 violations - Function length

  # Low effort to fix (under 100 violations)
  - sorted_imports # 428 violations - Import ordering
  - direct_return # 30 violations - Direct returns
  - function_default_parameter_at_end # 14 violations - Parameter order
  - superfluous_else # 14 violations - Else after return
  - explicit_enum_raw_value # 24 violations - Enum raw values
  - conditional_returns_on_newline # 6 violations - Return placement
  - redundant_self # 6 violations - Self in closures
  - pattern_matching_keywords # 4 violations - Pattern matching
  - let_var_whitespace # 36 violations - Variable spacing
  - unused_parameter # 202 violations - Unused parameters
  - anonymous_argument_in_multiline_closure # 30 violations - Named arguments
  - unhandled_throwing_task # 4 violations - Task error handling
  - operator_usage_whitespace # 8 violations - Operator spacing
  - no_grouping_extension # 40 violations - Extensions in same file
  - shorthand_optional_binding # 38 violations - Use shorthand syntax
  - multiline_arguments_brackets # 50 violations - Bracket placement
  - trailing_whitespace # 52 violations - Whitespace at line ends
  - non_overridable_class_declaration # 76 violations - Extension access modifiers
  - sorted_enum_cases # 28 violations - Enum case ordering
  - raw_value_for_camel_cased_codable_enum # 12 violations - Codable enum raw values
  - prefer_key_path # 26 violations - Use key paths
  - statement_position # 14 violations - Else placement (moved from below)
  - vertical_parameter_alignment_on_call # 12 violations - Parameter alignment
  - comma_inheritance # 18 violations - Comma separation in inheritance
  - file_name # 18 violations - File naming
  - no_empty_block # 22 violations - Empty code blocks
  - attributes # 16 violations - Attribute placement
  - prefer_self_in_static_references # 8 violations - Use Self
  - multiline_function_chains # 2 violations - Function chaining
  - untyped_error_in_catch # 4 violations - Error type in catch
  - multiple_closures_with_trailing_closure # 4 violations - Multiple closures
  - trailing_closure # 10 violations - Trailing closure syntax
  - discouraged_optional_collection # 10 violations - Prefer empty over optional
  - switch_case_on_newline # 10 violations - Switch case newlines
  - trailing_newline # 2 violations - File endings
  - discouraged_none_name # 2 violations - Case none naming

# Make rules strict
strict: true

# Directories to include/exclude during linting
included:
  - Sources
  - Tests
excluded:
  - .build

# Customize rule parameters
line_length:
  warning: 150
  error: 200
  # Ignore line length in test files and files with long URLs/strings
  ignores_function_declarations: true
  ignores_comments: true
  ignores_urls: true

# Allow more parameters for complex initializers and functions
function_parameter_count:
  warning: 7
  error: 10

# Large tuples are sometimes needed in tests
large_tuple:
  warning: 4
  error: 5


# Allow higher complexity for switch statements and decision trees
cyclomatic_complexity:
  warning: 12
  error: 15

# Allow longer type bodies for command pattern implementations and test suites
type_body_length:
  warning: 620
  error: 650

# Temporarily relaxing file length limits to get tests passing
# TODO: Refactor to reduce file sizes once concurrency issues are resolved
file_length:
  warning: 900
  error: 1000


custom_rules:
  no_direct_color_literals:
    name: "No direct Color literals"
    regex: '(^|[^A-Za-z0-9_])Color[.](red|green|blue|orange|yellow|pink|purple|gray|black|white|clear|primary|secondary)'
    message: "Use UIComponents Color tokens (UIComponents/Sources/UIComponents/Color.swift) instead of Color.red/Color.gray/etc."
    severity: error
  no_color_primary_secondary_shorthand:
    name: "No .primary/.secondary shorthand"
    regex: '[.](foregroundColor|foregroundStyle)[(][ ]*[.](primary|secondary)[ ]*[)]'
    message: "Use Color.textPrimary/Color.textSecondary (tokens) instead of .primary/.secondary."
    severity: error
  no_system_color_constructors:
    name: "No UIColor/NSColor construction"
    regex: '(^|[^A-Za-z0-9_])Color[(][ ]*(UIColor|NSColor)[.]'
    message: "Use UIComponents Color tokens backed by Assets.xcassets."
    severity: error
  no_rgb_color_construction:
    name: "No RGB Color construction"
    regex: '(^|[^A-Za-z0-9_])Color[(][ ]*(red[ ]*:|[.]sRGB)'
    message: "Define colors in UIComponents Assets.xcassets and expose via Color.swift."
    severity: error
  no_color_hex_initializer:
    name: "No Color(hex:) construction"
    regex: '(^|[^A-Za-z0-9_])(Color[(][ ]*hex[ ]*:|[.]init[(][ ]*hex[ ]*:)'
    message: "Use Color.userProvided(hex:) for user colors; otherwise define colors in Assets.xcassets."
    severity: error
