# SwiftLint configuration for DataAssets module

# Enable essential opt-in rules
opt_in_rules:
  - all

# Disable overly strict or problematic rules
disabled_rules:
  # Same as other modules
  - contrasted_opening_brace
  - explicit_acl
  - file_types_order
  - one_declaration_per_file
  - type_contents_order
  - redundant_type_annotation
  - extension_access_modifier

  # DataAssets is primarily data, so these don't apply
  - no_magic_numbers # Data contains many numbers
  - missing_docs # Data is self-documenting
  - explicit_type_interface # Data declarations are clear
  - explicit_top_level_acl # Public by design

  # Not needed for data module
  - required_deinit
  - convenience_type
  - nesting

  # Allow flexibility for data structures
  - file_length # Data files can be long
  - type_body_length # Data structures can be large
  - line_length # Data strings can be long

  # Other common exceptions
  - sorted_imports
  - direct_return
  - function_default_parameter_at_end
  - superfluous_else
  - explicit_enum_raw_value
  - conditional_returns_on_newline
  - redundant_self
  - pattern_matching_keywords
  - let_var_whitespace
  - unused_parameter
  - anonymous_argument_in_multiline_closure
  - unhandled_throwing_task
  - operator_usage_whitespace
  - no_grouping_extension
  - shorthand_optional_binding
  - multiline_arguments
  - multiline_arguments_brackets
  - trailing_whitespace
  - non_overridable_class_declaration
  - sorted_enum_cases
  - raw_value_for_camel_cased_codable_enum
  - prefer_key_path
  - statement_position
  - vertical_parameter_alignment_on_call
  - comma_inheritance
  - file_name
  - no_empty_block
  - attributes
  - prefer_self_in_static_references
  - multiline_function_chains
  - untyped_error_in_catch
  - multiple_closures_with_trailing_closure
  - trailing_closure
  - discouraged_optional_collection
  - switch_case_on_newline
  - trailing_newline
  - discouraged_none_name
  - indentation_width
  - vertical_whitespace_between_cases
  - number_separator
  - unused_closure_parameter
  - closure_body_length
  - function_body_length
  - no_extension_access_modifier
  - force_unwrapping
  - blanket_disable_command
  - superfluous_disable_command
  - for_where # Data processing patterns
  - identifier_name # Allow GB and test variable names with underscores

# Make rules strict
strict: true

# Directories to include/exclude during linting
included:
  - Sources
  - Tests
excluded:
  - .build
  - Package.swift


custom_rules:
  no_direct_color_literals:
    name: "No direct Color literals"
    regex: '(^|[^A-Za-z0-9_])Color[.](red|green|blue|orange|yellow|pink|purple|gray|black|white|clear|primary|secondary)'
    message: "Use UIComponents Color tokens (UIComponents/Sources/UIComponents/Color.swift) instead of Color.red/Color.gray/etc."
    severity: error
  no_color_primary_secondary_shorthand:
    name: "No .primary/.secondary shorthand"
    regex: '[.](foregroundColor|foregroundStyle)[(][ ]*[.](primary|secondary)[ ]*[)]'
    message: "Use Color.textPrimary/Color.textSecondary (tokens) instead of .primary/.secondary."
    severity: error
  no_system_color_constructors:
    name: "No UIColor/NSColor construction"
    regex: '(^|[^A-Za-z0-9_])Color[(][ ]*(UIColor|NSColor)[.]'
    message: "Use UIComponents Color tokens backed by Assets.xcassets."
    severity: error
  no_rgb_color_construction:
    name: "No RGB Color construction"
    regex: '(^|[^A-Za-z0-9_])Color[(][ ]*(red[ ]*:|[.]sRGB)'
    message: "Define colors in UIComponents Assets.xcassets and expose via Color.swift."
    severity: error
  no_color_hex_initializer:
    name: "No Color(hex:) construction"
    regex: '(^|[^A-Za-z0-9_])(Color[(][ ]*hex[ ]*:|[.]init[(][ ]*hex[ ]*:)'
    message: "Use Color.userProvided(hex:) for user colors; otherwise define colors in Assets.xcassets."
    severity: error
