import Abstractions
import Database
import SwiftUI

// MARK: - Constants

private enum ImageConstants {
    #if os(iOS) || os(visionOS)
        static let thumbnailSize: CGFloat = 300
    #elseif os(macOS)
        static let thumbnailSize: CGFloat = 400
    #endif

    static let borderColor: Color = .gray
    static let borderWidth: CGFloat = 1
}

// MARK: - Main ImageView

public struct ImageView: View {
    @Environment(\.imageHandler)
    var viewModel: ViewModelImaging

    @Bindable var attachment: ImageAttachment
    @State private var showingFullScreen: Bool = false

    public var body: some View {
        ZStack {
            if let platformImage = dataToPlatformImage(attachment.image) {
                mainImageContent(platformImage: platformImage)
            } else {
                Text(
                    String(
                        localized: "No Image",
                        bundle: .module,
                        comment: "No image available label"
                    )
                )
            }
        }
        .sheet(isPresented: $showingFullScreen) {
            FullScreenSheetContent(imageData: attachment.image)
        }
    }

    // MARK: - Private View Components

    private func mainImageContent(platformImage: PlatformImage) -> some View {
        Image(platformImage: platformImage)
            .resizable()
            .aspectRatio(contentMode: .fit)
            .frame(width: ImageConstants.thumbnailSize, height: ImageConstants.thumbnailSize)
            .clipped()
            .border(ImageConstants.borderColor, width: ImageConstants.borderWidth)
            .onTapGesture {
                showingFullScreen = true
            }
            .contextMenu {
                imageContextMenuContent(platformImage: platformImage)
            }
            .draggable(
                Image(platformImage: platformImage)
            )
            .accessibilityLabel(
                String(
                    localized: "Image generated by AI",
                    bundle: .module,
                    comment: "Accessibility label for image generated by AI"
                )
            )
            .accessibilityAddTraits(.isButton) // Adding button trait for tap gesture
    }

    @ViewBuilder
    private func imageContextMenuContent(platformImage: PlatformImage) -> some View {
        Button {
            viewModel.sharePlatformImage(platformImage)
        } label: {
            Label(
                String(
                    localized: "Share",
                    bundle: .module,
                    comment: "Share button label"
                ),
                systemImage: "square.and.arrow.up"
            )
        }

        Button {
            viewModel.savePlatformImage(platformImage)
        } label: {
            Label(
                String(localized: "Save", bundle: .module),
                systemImage: "square.and.arrow.down"
            )
        }

        Button {
            viewModel.copyPlatformImage(platformImage)
        } label: {
            Label(
                String(localized: "Copy", bundle: .module),
                systemImage: "doc.on.doc"
            )
        }
    }
}

// MARK: - Extensions

extension View {
    /// This extension is no longer needed as we're directly using constants
    @available(*, deprecated, message: "Use ImageConstants instead")
    func frameForPlatform() -> some View {
        self
    }
}

// MARK: - Preview

#if DEBUG
    #Preview {
        @Previewable @State var image: ImageAttachment = .preview
        ImageView(attachment: image)
    }
#endif
