# Enable all available rules
opt_in_rules:
  - all

disabled_rules:
  - contrasted_opening_brace
  - type_contents_order
  - redundant_type_annotation
  - extension_access_modifier

# Make rules strict
strict: true

# Directories to include/exclude during linting
included:
  - Sources
  - Tests
excluded:
  - .build

# Customize rule parameters
line_length:
  warning: 110
  error: 120

function_body_length:
  warning: 20
  error: 30 # Allow slightly longer test methods

cyclomatic_complexity:
  warning: 8
  error: 8
custom_rules:
  no_direct_color_literals:
    name: "No direct Color literals"
    regex: '\\bColor\\.(red|green|blue|orange|yellow|pink|purple|gray|black|white|clear|primary|secondary)\\b'
    message: "Use UIComponents Color tokens (UIComponents/Sources/UIComponents/Color.swift) instead of Color.red/Color.gray/etc."
    severity: error
  no_color_primary_secondary_shorthand:
    name: "No .primary/.secondary shorthand"
    regex: '\\.(foregroundColor|foregroundStyle)\\(\\s*\\.(primary|secondary)\\s*\\)'
    message: "Use Color.textPrimary/Color.textSecondary (tokens) instead of .primary/.secondary."
    severity: error
  no_system_color_constructors:
    name: "No UIColor/NSColor construction"
    regex: 'Color\\(\\s*(UIColor|NSColor)\\.'
    message: "Use UIComponents Color tokens backed by Assets.xcassets."
    severity: error
  no_rgb_color_construction:
    name: "No RGB Color construction"
    regex: 'Color\\(\\s*red\\s*:|Color\\(\\s*\\.sRGB'
    message: "Define colors in UIComponents Assets.xcassets and expose via Color.swift."
    severity: error
  no_color_hex_initializer:
    name: "No Color(hex:) construction"
    regex: 'Color\\(\\s*hex\\s*:|\\.init\\(\\s*hex\\s*:'
    message: "Use Color.userProvided(hex:) for user colors; otherwise define colors in Assets.xcassets."
    severity: error
